//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab4
{


    public partial class Forma
    {

        
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

      
        protected global::System.Web.UI.WebControls.Label Label1;

    
        protected global::System.Web.UI.WebControls.TextBox TextBox1;

     
        protected global::System.Web.UI.WebControls.Label Label2;

        protected global::System.Web.UI.WebControls.TextBox TextBox2;

      
        protected global::System.Web.UI.WebControls.Button Button1;

       
        protected global::System.Web.UI.WebControls.Table Table1;
    }
}
